# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Code
email: lplade@users.noreply.github.com
description: > # this means to ignore newlines until "baseurl:"
  Software projects for l.p.lade
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lplade.github.io" # the base hostname & protocol for your site
#twitter_username:
github_username:  lplade

# Build settings
markdown: kramdown
highlighter: rouge
